from pathlib import Path
from datetime import datetime
p=Path("gui.py")
text=p.read_text(encoding="utf-8", errors="ignore")
backup=Path(f"gui.py.bak_stale_cycle_{datetime.now().strftime('%Y%m%d_%H%M%S')}")
backup.write_text(text, encoding="utf-8")
changed=[]
needle="""    def _cycle_active_count(self) -> int:\n        return len(self._cycle_active_names())\n\n    def _cycle_watchdog(self):\n"""
insert="""    def _cycle_active_count(self) -> int:\n        return len(self._cycle_active_names())\n\n    def _cycle_clear_stale_enabled_flags(self, campaign_names) -> list[str]:\n        \"\"\"Disable DB campaigns that are marked enabled but have no live worker.\n\n        This keeps the UI and DB in sync after a worker exits early (empty text,\n        no account access, exception) and prevents Start/Stop from getting stuck\n        around stale enabled=1 rows.\n        \"\"\"\n        cleaned = []\n        names = [str(n).strip() for n in (campaign_names or []) if str(n).strip()]\n        if not names:\n            return cleaned\n        try:\n            db = Database(self.app.config.db_path)\n            try:\n                for name in names:\n                    try:\n                        cid = db.get_or_create_cycle_campaign(name)\n                        db.set_cycle_campaign_enabled(cid, False)\n                        cleaned.append(name)\n                    except Exception as e:\n                        self.log.append(f\"[Циклическая] [watchdog] Не смог сбросить '{name}': {e}\")\n            finally:\n                db.close()\n        except Exception as e:\n            try:\n                self.log.append(f\"[Циклическая] [watchdog] Не смог открыть БД для сброса зависших кампаний: {e}\")\n            except Exception:\n                pass\n        if cleaned:\n            try:\n                self.log.append(\"[Циклическая] [watchdog] Сбросил зависшее enabled=1 без живого воркера: \" + \", \".join(cleaned))\n            except Exception:\n                pass\n        return cleaned\n\n    def _cycle_watchdog(self):\n"""
if needle in text and "_cycle_clear_stale_enabled_flags" not in text:
    text=text.replace(needle, insert, 1); changed.append("added helper")
old="""            if enabled_with_targets and not active_names:\n                now = time.monotonic()\n                if now - getattr(self, \"_cycle_last_watchdog_log_at\", 0.0) > 300:\n                    self.log.append(\n                        \"[Циклическая] [watchdog] Кампании сохранены как активные, \"\n                        \"но живого фонового воркера нет: \" + \", \".join(enabled_with_targets)\n                    )\n                    self._cycle_last_watchdog_log_at = now\n                try:\n                    self._cycle_set_status(\n                        \"не работает: нет фонового воркера, нажми Старт для выбранной кампании\",\n                        \"#E74C3C\",\n                    )\n"""
new="""            if enabled_with_targets and not active_names:\n                cleaned = self._cycle_clear_stale_enabled_flags(enabled_with_targets)\n                now = time.monotonic()\n                if now - getattr(self, \"_cycle_last_watchdog_log_at\", 0.0) > 300:\n                    self.log.append(\n                        \"[Циклическая] [watchdog] Кампании были сохранены как активные, \"\n                        \"но живого фонового воркера нет: \" + \", \".join(enabled_with_targets)\n                    )\n                    if cleaned:\n                        self.log.append(\"[Циклическая] [watchdog] Статус очищен. Запускай кампанию заново после проверки текста/аккаунтов.\")\n                    self._cycle_last_watchdog_log_at = now\n                try:\n                    self._cycle_set_status(\n                        \"остановлен: фонового воркера нет, зависший статус сброшен\",\n                        \"#E74C3C\",\n                    )\n"""
if old in text:
    text=text.replace(old,new,1); changed.append("watchdog clears stale enabled")
else:
    changed.append("watchdog block not matched")
old="""        if runner is None:\n            if not self._cycle_runner_alive({\"thread\": thread}):\n                return\n            runner = {\n                \"thread\": thread,\n                \"stop_event\": getattr(self, \"_cycle_stop_event\", threading.Event()),\n                \"stop_requested_at\": None,\n            }\n"""
new="""        if runner is None:\n            if not self._cycle_runner_alive({\"thread\": thread}):\n                if campaign_name:\n                    try:\n                        self._cycle_disable_current_campaign(campaign_name)\n                        self.log.append(f\"[Циклическая] [=] Живого воркера нет; сбросил зависшее состояние кампании: {campaign_name}\")\n                        self._cycle_finish_stopped_ui(campaign_name)\n                    except Exception as e:\n                        try:\n                            self.log.append(f\"[Циклическая] [!] Не смог сбросить зависшее состояние '{campaign_name}': {e}\")\n                        except Exception:\n                            pass\n                return\n            runner = {\n                \"thread\": thread,\n                \"stop_event\": getattr(self, \"_cycle_stop_event\", threading.Event()),\n                \"stop_requested_at\": None,\n            }\n"""
if old in text:
    text=text.replace(old,new,1); changed.append("stop clears stale selected")
else:
    changed.append("stop block not matched")
p.write_text(text, encoding="utf-8")
print("backup", backup)
print("\n".join(changed))
